### ISSUE TITLE
Plugin not working on IE

### ISSUE THREAD

**Issue by zoolwiko** [maxiruani/mr-image#4]
Tested your demo page on IE 11 and it's not working, any idea why?

**Comment by zoolwiko** [comment]
Ok I've found out what's wrong. Check this: https://docs.angularjs.org/guide/ie

You have to make some changes in template for mrImage directive:

style="height: {{scaleValue(height, scale) + \'px\'}}; width: {{scaleValue(width, scale) + \'px\'}}"

to something like this:

ng-style="{ \'height\': scaleValuePx(height, scale), \'width\': scaleValuePx(width, scale)}

and add function 'scaleValuePx' which is a copy/paste of currently existing scaleValue function but it should return scaledValue + 'px':

scope.scaleValuePx = function (value, scale) {
                return Math.floor(value \* scale) + 'px';
            };

Tested it and it's working on IE >= 9.

**Comment by maxiruani** [comment]
Thanks @MarcinDr! You could fork the project and create a pull request of the fix, you will be added as a contributor then. Let me know if you want.

Thanks again!

**Comment by zoolwiko** [comment]
Sorry didn't use Github to much yet so i didn't know how :) I want to add one more thing - we are not using mrImageDrawer directive but it might be needed to change something in there too.

<i> Let me know if you want</i>, yes sure :dancers:

**Comment by maxiruani** [comment]
Merged and fixed.
